package org.acme.insurancenew;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Driver")
public class Driver implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   public Driver()
   {
   }

}