package org.acme.insurancenew;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Rejection")
public class Rejection implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   public Rejection()
   {
   }

}